### PR TITLE
feat: left sider width support drag

### PR DESCRIPTION
**Pull request by buqiyuan**

### CODE REVIEW

**Comment by scarqin** [comment]
@buqiyuan 
1.Drag bar is blocked
origin_img_v2_570184ba-544e-448d-bfee-d6e60a230d6g
2.Not remembering drag width

**Comment by buqiyuan** [comment]
> @buqiyuan 1.Drag bar is blocked origin_img_v2_570184ba-544e-448d-bfee-d6e60a230d6g 2.Not remembering drag width

done

**Comment by scarqin** [comment]
@buqiyuan lose focus when drag

https://user-images.githubusercontent.com/15225835/184122968-f0e4aa72-d4d5-4018-afa9-96f55ccfd6bd.mp4

**Comment by buqiyuan** [comment]
> lose focus when drag

fixed

**Pull request merged**
